"use client";

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Provider } from "react-redux";
import store from "../src/services/store"
import "./styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: Infinity,
      cacheTime: Infinity,
    },
  },
});

//export const metadata: Metadata = {
//  title: "Library",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <body className={inter.className}>
            <Header />
            {children}
				<footer style={{textAlign: 'center',
			padding: "50px 0"}}>
					<h1>Denis Odnourov & Shalkar Koshenayev</h1>
					<h3 style={{marginTop: 20}}>(CSE-2305 & CSE-2301)</h3>
				</footer>
          </body>
        </QueryClientProvider>
      </Provider>
    </html>
  );
}
